language: node_js
node_js:
- '0.12'
deploy:
  provider: npm
  email: gilbarbara@gmail.com
  api_key:
    secure: qMItZJoBg07NAI9C32NUQkCP8N2sVNCBTzRGiFFkKMdm2mtypXMgOny08HJdssUyx0F9J8OKhBziLKRhc5INpI9IrlpJp93Bo/DIxsTxI35CY07wvk6HU8c/Ju/va+jaNc0FSMDBiGe2CWb1R0wkaNkZC8cmUePZwi3wMRn1Y5F147DzaQX3duglig0/cNAKHCv69dHnmJ94YEYolPEvEwPnZOoFbRUCa3P8qLmHRG50vIiZUT620jc87xMEgtR7/xqYwVKal1NbRHOclgpiTnRlBqTqEoOMAoKWz+Zq+fDFsefwB3/oh3VcuViH08huXP4Ext+dz7zro4nK9BxhOBx1CUh2aHkS2ncNJb5k+x+4AO12ZQkRIbgRQeVAt8KP3H3rk7yPAk5f9Xlmw8+v4GlNWwXNsKtwrUxENme46xo4f77z/IF7zI4UvggUPJf1nxIWWzslVZ+yzTiMGzfahtGvopVLzZafjvCMU5yJUFP0ZQxTc4tzr1GkhQo3EEbxj/fCG7ZsGb3HGfGUAXo4k9bG6aQ40cUJ3gqGwiwfy4ZK7H9gB1g6rrVVwQnjJSiQEW3MDblfMy+6NO37WZI69DYJ8GqKfofJLVpJx9mmxPzU0YKRkY6OBdImn2EGKtXpit52iPDlAK8zLv0CSyEY+IRC/4leKGYm//oYcfqtGoU=
  on:
    tags: true
    repo: gilbarbara/react-joyride
